POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvaDA0IiwiaWQiOiI2NjlkOTE4YTY2MTBlZDBkYjMyMDA4MmEiLCJpYXQiOjE3MjE4NjAzNzYsImV4cCI6MTcyMTg2Mzk3Nn0.PErhcO4T528KZ7zyUyJHibZT-2tcm1SuEWs0QS5OAZk

{
  "_id":"5a422a851b54a676234daaaa",
  "title":"Hello World",
  "author":"Terry",
  "url":"www.hmmm.com",
  "likes":0
}