POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvaDA0IiwiaWQiOiI2NmFlNjI2NGMwMWY5NzVlOGUwNWVjZTUiLCJpYXQiOjE3MjI3MDQ0ODgsImV4cCI6MTcyMjcwODA4OH0.M1uqYUBGuVtG1gShAVBMG2KIQTaAtCBTErvy9c7Y3M8

{
  "_id":"5a422a851b54a676234daaaa",
  "title":"Hello World",
  "author":"Terry",
  "url":"www.hmmm.com",
  "likes":0
}