POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2ttYW4xMSIsImlkIjoiNjRjMmFmYzMyZGRlOTI3YzM3OTJhNWQ2IiwiaWF0IjoxNjkwNDg1NjE1fQ.wryiaD0bQ6I2wdMNeje_DH4qDzqyp429j_bXvh6Zx_Y

{ 
    "title": "This Horse Knows Karate?!",
    "author": "fistkickkid22",
    "url": "www.karatehorse.com",
    "likes": 91
}