DELETE http://localhost:3003/api/blogs/64c2c44d6a534ee80d7289ed
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2ttYW4xMSIsImlkIjoiNjRjMmFmYzMyZGRlOTI3YzM3OTJhNWQ2IiwiaWF0IjoxNjkwNDg1NjE1fQ.wryiaD0bQ6I2wdMNeje_DH4qDzqyp429j_bXvh6Zx_Y
